package org.eclipse.ice.dev.annotations;

import static org.junit.jupiter.api.Assertions.*;

import org.eclipse.ice.dev.annotations.processors.Field;
import org.eclipse.ice.dev.annotations.processors.Field.FieldBuilder;
import org.junit.jupiter.api.Test;

/**
 * Tests for FieldBuilder class.
 *
 * Methods generated by Lombok not tested.
 * @author Daniel Bluhm
 */
class FieldBuilderTest {

	@Test
	void testDefaultValue() {
		FieldBuilder builder = Field.builder();

		// Boolean
		builder.defaultValue(true);
		assertEquals("true", builder.build().getDefaultValue());

		// Long
		builder.defaultValue(10L);
		assertEquals("10L", builder.build().getDefaultValue());

		// String
		builder.defaultValue("test");
		assertEquals("\"test\"", builder.build().getDefaultValue());

		// Raw
		builder.defaultValue(Field.raw("test"));
		assertEquals("test", builder.build().getDefaultValue());
	}

	@Test
	void testTypeNonPrimitive() {
		FieldBuilder builder = Field.builder();
		Field f;

		// Class<?> non-primitive
		builder.type(String.class);
		f = builder.build();
		assertEquals("java.lang.String", f.getType());
		assertFalse(f.isPrimitive());
	}

	@Test
	void testTypePrimitive() {
		FieldBuilder builder = Field.builder();
		Field f;

		// Class<?> primitive
		builder.type(int.class);
		f = builder.build();
		assertEquals("int", f.getType());
		assertTrue(f.isPrimitive());
	}

	@Test
	void testTypeRaw() {
		FieldBuilder builder = Field.builder();
		Field f;

		// Raw
		builder.type(Field.raw("java.util.Date"));
		f = builder.build();
		assertEquals("java.util.Date", f.getType());
		// While Dates are not primitive values, because the type is set
		// as a raw value, the builder will not set whether the type
		// is primitive or not; that must be manually specified
		// when using Raw.
		assertFalse(f.isPrimitive());
	}

	@Test
	void testTypeRawFake() {
		FieldBuilder builder = Field.builder();
		Field f;

		builder = Field.builder();
		// Raw - not a real class
		builder.type(Field.raw("Asdf"));
		f = builder.build();
		assertEquals("Asdf", f.getType());
		assertFalse(f.isPrimitive());
	}

	@Test
	void testGuessTypeFromJsonPrimitive() {
		FieldBuilder builder = Field.builder();
		Field f;

		// Guess primitive
		builder.jsonType("int");
		f = builder.build();
		assertEquals("int", f.getType());
		assertTrue(f.isPrimitive());
	}

	@Test
	void testGuessTypeFromJsonNonPrimitive() {
		FieldBuilder builder = Field.builder();
		Field f;

		// Guess non-primitive
		builder.jsonType("String");
		f = builder.build();
		assertEquals("java.lang.String", f.getType());
		assertFalse(f.isPrimitive());
	}

	@Test
	void testGuessTypeFromJsonNonPrimitiveOutsideOfLang() {
		FieldBuilder builder = Field.builder();
		Field f;

		// Guess non-primitive
		builder.jsonType("java.util.Date");
		f = builder.build();
		assertEquals("java.util.Date", f.getType());
		assertFalse(f.isPrimitive());
	}

	@Test
	void testJsonTypeStringEscapesDefaultValue() {
		FieldBuilder builder = Field.builder();
		Field f;

		// Default value set first
		builder.jsonDefaultValue("test");
		builder.jsonType("String");
		f = builder.build();
		assertEquals("\"test\"", f.getDefaultValue());

		// Now reversed; type set first
		builder = Field.builder();
		builder.jsonType("String");
		builder.jsonDefaultValue("test");
		f = builder.build();
		assertEquals("\"test\"", f.getDefaultValue());
	}
}
