/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.ice.exodusII;

public class ex_block {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ex_block(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ex_block obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exodusIIJNI.delete_ex_block(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_block_id_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getId() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_block_id_get(swigCPtr, this), true);
  }

  public void setType(ex_entity_type value) {
    exodusIIJNI.ex_block_type_set(swigCPtr, this, value.swigValue());
  }

  public ex_entity_type getType() {
    return ex_entity_type.swigToEnum(exodusIIJNI.ex_block_type_get(swigCPtr, this));
  }

  public void setTopology(String value) {
    exodusIIJNI.ex_block_topology_set(swigCPtr, this, value);
  }

  public String getTopology() {
    return exodusIIJNI.ex_block_topology_get(swigCPtr, this);
  }

  public void setNum_entry(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_block_num_entry_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_entry() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_block_num_entry_get(swigCPtr, this), true);
  }

  public void setNum_nodes_per_entry(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_block_num_nodes_per_entry_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_nodes_per_entry() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_block_num_nodes_per_entry_get(swigCPtr, this), true);
  }

  public void setNum_edges_per_entry(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_block_num_edges_per_entry_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_edges_per_entry() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_block_num_edges_per_entry_get(swigCPtr, this), true);
  }

  public void setNum_faces_per_entry(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_block_num_faces_per_entry_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_faces_per_entry() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_block_num_faces_per_entry_get(swigCPtr, this), true);
  }

  public void setNum_attribute(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_block_num_attribute_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_attribute() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_block_num_attribute_get(swigCPtr, this), true);
  }

  public ex_block() {
    this(exodusIIJNI.new_ex_block(), true);
  }

}
