/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.ice.exodusII;

public final class ex_entity_type {
  public final static ex_entity_type EX_NODAL = new ex_entity_type("EX_NODAL", exodusIIJNI.EX_NODAL_get());
  public final static ex_entity_type EX_NODE_BLOCK = new ex_entity_type("EX_NODE_BLOCK", exodusIIJNI.EX_NODE_BLOCK_get());
  public final static ex_entity_type EX_NODE_SET = new ex_entity_type("EX_NODE_SET", exodusIIJNI.EX_NODE_SET_get());
  public final static ex_entity_type EX_EDGE_BLOCK = new ex_entity_type("EX_EDGE_BLOCK", exodusIIJNI.EX_EDGE_BLOCK_get());
  public final static ex_entity_type EX_EDGE_SET = new ex_entity_type("EX_EDGE_SET", exodusIIJNI.EX_EDGE_SET_get());
  public final static ex_entity_type EX_FACE_BLOCK = new ex_entity_type("EX_FACE_BLOCK", exodusIIJNI.EX_FACE_BLOCK_get());
  public final static ex_entity_type EX_FACE_SET = new ex_entity_type("EX_FACE_SET", exodusIIJNI.EX_FACE_SET_get());
  public final static ex_entity_type EX_ELEM_BLOCK = new ex_entity_type("EX_ELEM_BLOCK", exodusIIJNI.EX_ELEM_BLOCK_get());
  public final static ex_entity_type EX_ELEM_SET = new ex_entity_type("EX_ELEM_SET", exodusIIJNI.EX_ELEM_SET_get());
  public final static ex_entity_type EX_SIDE_SET = new ex_entity_type("EX_SIDE_SET", exodusIIJNI.EX_SIDE_SET_get());
  public final static ex_entity_type EX_ELEM_MAP = new ex_entity_type("EX_ELEM_MAP", exodusIIJNI.EX_ELEM_MAP_get());
  public final static ex_entity_type EX_NODE_MAP = new ex_entity_type("EX_NODE_MAP", exodusIIJNI.EX_NODE_MAP_get());
  public final static ex_entity_type EX_EDGE_MAP = new ex_entity_type("EX_EDGE_MAP", exodusIIJNI.EX_EDGE_MAP_get());
  public final static ex_entity_type EX_FACE_MAP = new ex_entity_type("EX_FACE_MAP", exodusIIJNI.EX_FACE_MAP_get());
  public final static ex_entity_type EX_GLOBAL = new ex_entity_type("EX_GLOBAL", exodusIIJNI.EX_GLOBAL_get());
  public final static ex_entity_type EX_COORDINATE = new ex_entity_type("EX_COORDINATE", exodusIIJNI.EX_COORDINATE_get());
  public final static ex_entity_type EX_INVALID = new ex_entity_type("EX_INVALID", exodusIIJNI.EX_INVALID_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ex_entity_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ex_entity_type.class + " with value " + swigValue);
  }

  private ex_entity_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ex_entity_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ex_entity_type(String swigName, ex_entity_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ex_entity_type[] swigValues = { EX_NODAL, EX_NODE_BLOCK, EX_NODE_SET, EX_EDGE_BLOCK, EX_EDGE_SET, EX_FACE_BLOCK, EX_FACE_SET, EX_ELEM_BLOCK, EX_ELEM_SET, EX_SIDE_SET, EX_ELEM_MAP, EX_NODE_MAP, EX_EDGE_MAP, EX_FACE_MAP, EX_GLOBAL, EX_COORDINATE, EX_INVALID };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

