/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.ice.exodusII;

public class ex_init_params {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ex_init_params(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ex_init_params obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exodusIIJNI.delete_ex_init_params(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTitle(String value) {
    exodusIIJNI.ex_init_params_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return exodusIIJNI.ex_init_params_title_get(swigCPtr, this);
  }

  public void setNum_dim(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_dim_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_dim() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_dim_get(swigCPtr, this), true);
  }

  public void setNum_nodes(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_nodes_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_nodes() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_nodes_get(swigCPtr, this), true);
  }

  public void setNum_edge(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_edge_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_edge() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_edge_get(swigCPtr, this), true);
  }

  public void setNum_edge_blk(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_edge_blk_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_edge_blk() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_edge_blk_get(swigCPtr, this), true);
  }

  public void setNum_face(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_face_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_face() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_face_get(swigCPtr, this), true);
  }

  public void setNum_face_blk(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_face_blk_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_face_blk() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_face_blk_get(swigCPtr, this), true);
  }

  public void setNum_elem(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_elem_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_elem() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_elem_get(swigCPtr, this), true);
  }

  public void setNum_elem_blk(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_elem_blk_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_elem_blk() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_elem_blk_get(swigCPtr, this), true);
  }

  public void setNum_node_sets(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_node_sets_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_node_sets() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_node_sets_get(swigCPtr, this), true);
  }

  public void setNum_edge_sets(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_edge_sets_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_edge_sets() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_edge_sets_get(swigCPtr, this), true);
  }

  public void setNum_face_sets(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_face_sets_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_face_sets() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_face_sets_get(swigCPtr, this), true);
  }

  public void setNum_side_sets(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_side_sets_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_side_sets() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_side_sets_get(swigCPtr, this), true);
  }

  public void setNum_elem_sets(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_elem_sets_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_elem_sets() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_elem_sets_get(swigCPtr, this), true);
  }

  public void setNum_node_maps(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_node_maps_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_node_maps() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_node_maps_get(swigCPtr, this), true);
  }

  public void setNum_edge_maps(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_edge_maps_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_edge_maps() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_edge_maps_get(swigCPtr, this), true);
  }

  public void setNum_face_maps(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_face_maps_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_face_maps() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_face_maps_get(swigCPtr, this), true);
  }

  public void setNum_elem_maps(SWIGTYPE_p_int64_t value) {
    exodusIIJNI.ex_init_params_num_elem_maps_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getNum_elem_maps() {
    return new SWIGTYPE_p_int64_t(exodusIIJNI.ex_init_params_num_elem_maps_get(swigCPtr, this), true);
  }

  public ex_init_params() {
    this(exodusIIJNI.new_ex_init_params(), true);
  }

}
