/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.ice.exodusII;

public final class ex_option_type {
  public final static ex_option_type EX_OPT_MAX_NAME_LENGTH = new ex_option_type("EX_OPT_MAX_NAME_LENGTH", exodusIIJNI.EX_OPT_MAX_NAME_LENGTH_get());
  public final static ex_option_type EX_OPT_COMPRESSION_TYPE = new ex_option_type("EX_OPT_COMPRESSION_TYPE");
  public final static ex_option_type EX_OPT_COMPRESSION_LEVEL = new ex_option_type("EX_OPT_COMPRESSION_LEVEL");
  public final static ex_option_type EX_OPT_COMPRESSION_SHUFFLE = new ex_option_type("EX_OPT_COMPRESSION_SHUFFLE");
  public final static ex_option_type EX_OPT_INTEGER_SIZE_API = new ex_option_type("EX_OPT_INTEGER_SIZE_API");
  public final static ex_option_type EX_OPT_INTEGER_SIZE_DB = new ex_option_type("EX_OPT_INTEGER_SIZE_DB");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ex_option_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ex_option_type.class + " with value " + swigValue);
  }

  private ex_option_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ex_option_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ex_option_type(String swigName, ex_option_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ex_option_type[] swigValues = { EX_OPT_MAX_NAME_LENGTH, EX_OPT_COMPRESSION_TYPE, EX_OPT_COMPRESSION_LEVEL, EX_OPT_COMPRESSION_SHUFFLE, EX_OPT_INTEGER_SIZE_API, EX_OPT_INTEGER_SIZE_DB };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

