/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.ice.exodusII;

public final class ex_options {
  public final static ex_options EX_DEFAULT = new ex_options("EX_DEFAULT", exodusIIJNI.EX_DEFAULT_get());
  public final static ex_options EX_VERBOSE = new ex_options("EX_VERBOSE", exodusIIJNI.EX_VERBOSE_get());
  public final static ex_options EX_DEBUG = new ex_options("EX_DEBUG", exodusIIJNI.EX_DEBUG_get());
  public final static ex_options EX_ABORT = new ex_options("EX_ABORT", exodusIIJNI.EX_ABORT_get());
  public final static ex_options EX_NULLVERBOSE = new ex_options("EX_NULLVERBOSE", exodusIIJNI.EX_NULLVERBOSE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ex_options swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ex_options.class + " with value " + swigValue);
  }

  private ex_options(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ex_options(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ex_options(String swigName, ex_options swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ex_options[] swigValues = { EX_DEFAULT, EX_VERBOSE, EX_DEBUG, EX_ABORT, EX_NULLVERBOSE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

