/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.ice.exodusII;

public class ex_var_params {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ex_var_params(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ex_var_params obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exodusIIJNI.delete_ex_var_params(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_glob(int value) {
    exodusIIJNI.ex_var_params_num_glob_set(swigCPtr, this, value);
  }

  public int getNum_glob() {
    return exodusIIJNI.ex_var_params_num_glob_get(swigCPtr, this);
  }

  public void setNum_node(int value) {
    exodusIIJNI.ex_var_params_num_node_set(swigCPtr, this, value);
  }

  public int getNum_node() {
    return exodusIIJNI.ex_var_params_num_node_get(swigCPtr, this);
  }

  public void setNum_edge(int value) {
    exodusIIJNI.ex_var_params_num_edge_set(swigCPtr, this, value);
  }

  public int getNum_edge() {
    return exodusIIJNI.ex_var_params_num_edge_get(swigCPtr, this);
  }

  public void setNum_face(int value) {
    exodusIIJNI.ex_var_params_num_face_set(swigCPtr, this, value);
  }

  public int getNum_face() {
    return exodusIIJNI.ex_var_params_num_face_get(swigCPtr, this);
  }

  public void setNum_elem(int value) {
    exodusIIJNI.ex_var_params_num_elem_set(swigCPtr, this, value);
  }

  public int getNum_elem() {
    return exodusIIJNI.ex_var_params_num_elem_get(swigCPtr, this);
  }

  public void setNum_nset(int value) {
    exodusIIJNI.ex_var_params_num_nset_set(swigCPtr, this, value);
  }

  public int getNum_nset() {
    return exodusIIJNI.ex_var_params_num_nset_get(swigCPtr, this);
  }

  public void setNum_eset(int value) {
    exodusIIJNI.ex_var_params_num_eset_set(swigCPtr, this, value);
  }

  public int getNum_eset() {
    return exodusIIJNI.ex_var_params_num_eset_get(swigCPtr, this);
  }

  public void setNum_fset(int value) {
    exodusIIJNI.ex_var_params_num_fset_set(swigCPtr, this, value);
  }

  public int getNum_fset() {
    return exodusIIJNI.ex_var_params_num_fset_get(swigCPtr, this);
  }

  public void setNum_sset(int value) {
    exodusIIJNI.ex_var_params_num_sset_set(swigCPtr, this, value);
  }

  public int getNum_sset() {
    return exodusIIJNI.ex_var_params_num_sset_get(swigCPtr, this);
  }

  public void setNum_elset(int value) {
    exodusIIJNI.ex_var_params_num_elset_set(swigCPtr, this, value);
  }

  public int getNum_elset() {
    return exodusIIJNI.ex_var_params_num_elset_get(swigCPtr, this);
  }

  public void setEdge_var_tab(SWIGTYPE_p_int value) {
    exodusIIJNI.ex_var_params_edge_var_tab_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getEdge_var_tab() {
    long cPtr = exodusIIJNI.ex_var_params_edge_var_tab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setFace_var_tab(SWIGTYPE_p_int value) {
    exodusIIJNI.ex_var_params_face_var_tab_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFace_var_tab() {
    long cPtr = exodusIIJNI.ex_var_params_face_var_tab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setElem_var_tab(SWIGTYPE_p_int value) {
    exodusIIJNI.ex_var_params_elem_var_tab_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getElem_var_tab() {
    long cPtr = exodusIIJNI.ex_var_params_elem_var_tab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setNset_var_tab(SWIGTYPE_p_int value) {
    exodusIIJNI.ex_var_params_nset_var_tab_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getNset_var_tab() {
    long cPtr = exodusIIJNI.ex_var_params_nset_var_tab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setEset_var_tab(SWIGTYPE_p_int value) {
    exodusIIJNI.ex_var_params_eset_var_tab_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getEset_var_tab() {
    long cPtr = exodusIIJNI.ex_var_params_eset_var_tab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setFset_var_tab(SWIGTYPE_p_int value) {
    exodusIIJNI.ex_var_params_fset_var_tab_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFset_var_tab() {
    long cPtr = exodusIIJNI.ex_var_params_fset_var_tab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setSset_var_tab(SWIGTYPE_p_int value) {
    exodusIIJNI.ex_var_params_sset_var_tab_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getSset_var_tab() {
    long cPtr = exodusIIJNI.ex_var_params_sset_var_tab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setElset_var_tab(SWIGTYPE_p_int value) {
    exodusIIJNI.ex_var_params_elset_var_tab_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getElset_var_tab() {
    long cPtr = exodusIIJNI.ex_var_params_elset_var_tab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ex_var_params() {
    this(exodusIIJNI.new_ex_var_params(), true);
  }

}
