/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.ice.exodusII;

public interface exodusIIConstants {
  public final static int EXODUSII_VERSION_MAJOR = exodusIIJNI.EXODUSII_VERSION_MAJOR_get();
  public final static int EXODUSII_VERSION_MINOR = exodusIIJNI.EXODUSII_VERSION_MINOR_get();
  public final static int EXODUSII_VERSION_PATCH = exodusIIJNI.EXODUSII_VERSION_PATCH_get();
  public final static String EXODUSII_VERSION = exodusIIJNI.EXODUSII_VERSION_get();
  public final static double EX_API_VERS = exodusIIJNI.EX_API_VERS_get();
  public final static int EX_API_VERS_NODOT = exodusIIJNI.EX_API_VERS_NODOT_get();
  public final static double EX_VERS = exodusIIJNI.EX_VERS_get();
  public final static double NEMESIS_API_VERSION = exodusIIJNI.NEMESIS_API_VERSION_get();
  public final static int NEMESIS_API_VERSION_NODOT = exodusIIJNI.NEMESIS_API_VERSION_NODOT_get();
  public final static double NEMESIS_FILE_VERSION = exodusIIJNI.NEMESIS_FILE_VERSION_get();
  public final static int EX_TRUE = exodusIIJNI.EX_TRUE_get();
  public final static int EX_FALSE = exodusIIJNI.EX_FALSE_get();
  public final static int EX_WRITE = exodusIIJNI.EX_WRITE_get();
  public final static int EX_READ = exodusIIJNI.EX_READ_get();
  public final static int EX_NOCLOBBER = exodusIIJNI.EX_NOCLOBBER_get();
  public final static int EX_CLOBBER = exodusIIJNI.EX_CLOBBER_get();
  public final static int EX_NORMAL_MODEL = exodusIIJNI.EX_NORMAL_MODEL_get();
  public final static int EX_LARGE_MODEL = exodusIIJNI.EX_LARGE_MODEL_get();
  public final static int EX_NETCDF4 = exodusIIJNI.EX_NETCDF4_get();
  public final static int EX_NOSHARE = exodusIIJNI.EX_NOSHARE_get();
  public final static int EX_SHARE = exodusIIJNI.EX_SHARE_get();
  public final static int EX_NOCLASSIC = exodusIIJNI.EX_NOCLASSIC_get();
  public final static int EX_MAPS_INT64_DB = exodusIIJNI.EX_MAPS_INT64_DB_get();
  public final static int EX_IDS_INT64_DB = exodusIIJNI.EX_IDS_INT64_DB_get();
  public final static int EX_BULK_INT64_DB = exodusIIJNI.EX_BULK_INT64_DB_get();
  public final static int EX_ALL_INT64_DB = exodusIIJNI.EX_ALL_INT64_DB_get();
  public final static int EX_MAPS_INT64_API = exodusIIJNI.EX_MAPS_INT64_API_get();
  public final static int EX_IDS_INT64_API = exodusIIJNI.EX_IDS_INT64_API_get();
  public final static int EX_BULK_INT64_API = exodusIIJNI.EX_BULK_INT64_API_get();
  public final static int EX_INQ_INT64_API = exodusIIJNI.EX_INQ_INT64_API_get();
  public final static int EX_ALL_INT64_API = exodusIIJNI.EX_ALL_INT64_API_get();
  public final static int EX_MPIIO = exodusIIJNI.EX_MPIIO_get();
  public final static int EX_MPIPOSIX = exodusIIJNI.EX_MPIPOSIX_get();
  public final static int EX_PNETCDF = exodusIIJNI.EX_PNETCDF_get();
  public final static int EX_INVALID_ID = exodusIIJNI.EX_INVALID_ID_get();
  public final static int MAX_STR_LENGTH = exodusIIJNI.MAX_STR_LENGTH_get();
  public final static int MAX_NAME_LENGTH = exodusIIJNI.MAX_NAME_LENGTH_get();
  public final static int MAX_LINE_LENGTH = exodusIIJNI.MAX_LINE_LENGTH_get();
  public final static int MAX_ERR_LENGTH = exodusIIJNI.MAX_ERR_LENGTH_get();
  public final static int EX_MEMFAIL = exodusIIJNI.EX_MEMFAIL_get();
  public final static int EX_BADFILEMODE = exodusIIJNI.EX_BADFILEMODE_get();
  public final static int EX_BADFILEID = exodusIIJNI.EX_BADFILEID_get();
  public final static int EX_WRONGFILETYPE = exodusIIJNI.EX_WRONGFILETYPE_get();
  public final static int EX_LOOKUPFAIL = exodusIIJNI.EX_LOOKUPFAIL_get();
  public final static int EX_BADPARAM = exodusIIJNI.EX_BADPARAM_get();
  public final static int EX_MSG = exodusIIJNI.EX_MSG_get();
  public final static int EX_PRTLASTMSG = exodusIIJNI.EX_PRTLASTMSG_get();
  public final static int EX_NOTROOTID = exodusIIJNI.EX_NOTROOTID_get();
  public final static int EX_NULLENTITY = exodusIIJNI.EX_NULLENTITY_get();
}
