<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="environment" nsURI="http://eclipse.org/ice/apps/docker" nsPrefix="dockerenvironment">
  <eClassifiers xsi:type="ecore:EClass" name="DockerEnvironment" eSuperTypes="../../org.eclipse.ice.developer.apps/model/apps.ecore#//IEnvironment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The DockerEnvironment is a realization of the IEnvironment interface that provides a launch method to create a scientific application environment in a Docker container. "/>
    </eAnnotations>
    <eOperations name="execute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="imageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="command" eType="ecore:EDataType ../../org.eclipse.ice.docker/model/org.eclipse.ice.docker.ecore#//CommandList"/>
    </eOperations>
    <eOperations name="hasDocker" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="pullImage">
      <eParameters name="imageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerConfiguration"
        eType="ecore:EClass ../../org.eclipse.ice.docker/model/org.eclipse.ice.docker.ecore#//ContainerConfiguration"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the container configuration data needed to launch a new docker container. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dockerfile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the String contents of the Dockerfile created to model this DockerEnvironment."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dockerAPI" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ice.docker/model/org.eclipse.ice.docker.ecore#//DockerAPI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DockerProjectLauncher" eSuperTypes="../../org.eclipse.ice.developer.apps/model/apps.ecore#//ProjectLauncher">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The DockerPTPProjectLauncher provides a launchProject method that uses the ContainerConfiguration of the current DockerEnvironment to create a new PTP Synchronized Project for the IEnvironment's primary application running in the created docker container. "/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Thing"/>
    </eAnnotations>
    <eOperations name="launchProject" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Launch the new Eclipse project for the given application. "/>
      </eAnnotations>
      <eParameters name="project" eType="ecore:EClass ../../org.eclipse.ice.developer.apps/model/apps.ecore#//SourcePackage"/>
    </eOperations>
    <eOperations name="updateConnection">
      <eParameters name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerconfiguration"
        eType="ecore:EClass ../../org.eclipse.ice.docker/model/org.eclipse.ice.docker.ecore#//ContainerConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DockerEnvironmentBuilder" eSuperTypes="../../org.eclipse.ice.developer.apps/model/apps.ecore#//EnvironmentBuilder"/>
</ecore:EPackage>
