/******************************************************************************
 * Copyright (c) 2020- UT-Battelle, LLC.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Initial API and implementation and/or initial documentation - 
 *   Jay Jay Billings
 *****************************************************************************/
package org.eclipse.ice.tasks;

import org.eclipse.ice.dev.annotations.DataElement;
import org.eclipse.ice.dev.annotations.DataField;

/**
 * The task state data spec that defines the state data for tasks. Note that
 * the actual TaskStateData class is autogenerated from this specification.
 * 
 * Further note that this spec does not define any type of persistence for the
 * task state data. That is consistent with requirement from ITask that tasks
 * store state in memory by default if no otherwise configured state data is
 * provided. This is properly handled by creating a Data Model with an
 * @Persisted annotation on its TaskStateData.
 * 
 * @author Jay Jay Billings
 *
 */
@DataElement(name="TaskStateData")
public class TaskStateDataSpec {

	/**
	 * The state of the task
	 */
	@DataField.Default(value = "org.eclipse.ice.tasks.TaskState.INITIALIZED")
	@DataField
	private TaskState taskState;
	
}
