//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 11:59:10 AM EDT 
//


package org.eclipse.ice.datastructures.batteryml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Base type for all list series values. Can have multiple elements. To be restricted.
 * 
 * <p>Java class for AnyListValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnyListValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{BatteryML:2.0}Int32List"/>
 *           &lt;element ref="{BatteryML:2.0}Int64List"/>
 *           &lt;element ref="{BatteryML:2.0}PositiveIntList"/>
 *           &lt;element ref="{BatteryML:2.0}NonNegativeIntList"/>
 *           &lt;element ref="{BatteryML:2.0}NonNegativeInt32List"/>
 *           &lt;element ref="{BatteryML:2.0}NonNegativeInt64List"/>
 *           &lt;element ref="{BatteryML:2.0}Float32List"/>
 *           &lt;element ref="{BatteryML:2.0}Float64List"/>
 *           &lt;element ref="{BatteryML:2.0}ShortNameList"/>
 *           &lt;element ref="{BatteryML:2.0}BooleanList"/>
 *           &lt;element ref="{BatteryML:2.0}DateTimeList"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnyListValueType", propOrder = {
    "int32ListOrInt64ListOrPositiveIntList"
})
@XmlSeeAlso({
    AnyListNumericValueType.class
})
public class AnyListValueType {

    @XmlElementRefs({
        @XmlElementRef(name = "Int32List", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "Float64List", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "Int64List", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "ShortNameList", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "PositiveIntList", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "NonNegativeInt64List", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "NonNegativeIntList", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "BooleanList", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "Float32List", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "DateTimeList", namespace = "BatteryML:2.0", type = JAXBElement.class),
        @XmlElementRef(name = "NonNegativeInt32List", namespace = "BatteryML:2.0", type = JAXBElement.class)
    })
    protected List<JAXBElement<? extends List<?>>> int32ListOrInt64ListOrPositiveIntList;

    /**
     * Gets the value of the int32ListOrInt64ListOrPositiveIntList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the int32ListOrInt64ListOrPositiveIntList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInt32ListOrInt64ListOrPositiveIntList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link Integer }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link Double }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link Long }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link Long }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigInteger }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link Long }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link Boolean }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link Float }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link Long }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link XMLGregorianCalendar }{@code >}{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends List<?>>> getInt32ListOrInt64ListOrPositiveIntList() {
        if (int32ListOrInt64ListOrPositiveIntList == null) {
            int32ListOrInt64ListOrPositiveIntList = new ArrayList<JAXBElement<? extends List<?>>>();
        }
        return this.int32ListOrInt64ListOrPositiveIntList;
    }

}
