//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 11:59:10 AM EDT 
//


package org.eclipse.ice.datastructures.batteryml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Base type for all single numeric list values.
 * 
 * <p>Java class for AnySingleListNumericValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnySingleListNumericValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{BatteryML:2.0}AnySingleListValueType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{BatteryML:2.0}Int32List"/>
 *           &lt;element ref="{BatteryML:2.0}Int64List"/>
 *           &lt;element ref="{BatteryML:2.0}PositiveIntList"/>
 *           &lt;element ref="{BatteryML:2.0}NonNegativeIntList"/>
 *           &lt;element ref="{BatteryML:2.0}NonNegativeInt32List"/>
 *           &lt;element ref="{BatteryML:2.0}NonNegativeInt64List"/>
 *           &lt;element ref="{BatteryML:2.0}Float32List"/>
 *           &lt;element ref="{BatteryML:2.0}Float64List"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnySingleListNumericValueType")
@XmlSeeAlso({
    AnySingleListCounterValueType.class
})
public class AnySingleListNumericValueType
    extends AnySingleListValueType
{


}
