//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 11:59:10 AM EDT 
//


package org.eclipse.ice.datastructures.batteryml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChemicalElementSymbolType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChemicalElementSymbolType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="He"/>
 *     &lt;enumeration value="Li"/>
 *     &lt;enumeration value="Be"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="Ne"/>
 *     &lt;enumeration value="Na"/>
 *     &lt;enumeration value="Mg"/>
 *     &lt;enumeration value="Al"/>
 *     &lt;enumeration value="Si"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="Cl"/>
 *     &lt;enumeration value="Ar"/>
 *     &lt;enumeration value="K"/>
 *     &lt;enumeration value="Ca"/>
 *     &lt;enumeration value="Sc"/>
 *     &lt;enumeration value="Ti"/>
 *     &lt;enumeration value="V"/>
 *     &lt;enumeration value="Cr"/>
 *     &lt;enumeration value="Mn"/>
 *     &lt;enumeration value="Fe"/>
 *     &lt;enumeration value="Co"/>
 *     &lt;enumeration value="Ni"/>
 *     &lt;enumeration value="Cu"/>
 *     &lt;enumeration value="Zn"/>
 *     &lt;enumeration value="Ga"/>
 *     &lt;enumeration value="Ge"/>
 *     &lt;enumeration value="As"/>
 *     &lt;enumeration value="Se"/>
 *     &lt;enumeration value="Br"/>
 *     &lt;enumeration value="Kr"/>
 *     &lt;enumeration value="Rb"/>
 *     &lt;enumeration value="Sr"/>
 *     &lt;enumeration value="Y"/>
 *     &lt;enumeration value="Zr"/>
 *     &lt;enumeration value="Nb"/>
 *     &lt;enumeration value="Mo"/>
 *     &lt;enumeration value="Tc"/>
 *     &lt;enumeration value="Ru"/>
 *     &lt;enumeration value="Rh"/>
 *     &lt;enumeration value="Pd"/>
 *     &lt;enumeration value="Ag"/>
 *     &lt;enumeration value="Cd"/>
 *     &lt;enumeration value="In"/>
 *     &lt;enumeration value="Sn"/>
 *     &lt;enumeration value="Sb"/>
 *     &lt;enumeration value="Te"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="Xe"/>
 *     &lt;enumeration value="Cs"/>
 *     &lt;enumeration value="Ba"/>
 *     &lt;enumeration value="La"/>
 *     &lt;enumeration value="Ce"/>
 *     &lt;enumeration value="Pr"/>
 *     &lt;enumeration value="Nd"/>
 *     &lt;enumeration value="Pm"/>
 *     &lt;enumeration value="Sm"/>
 *     &lt;enumeration value="Eu"/>
 *     &lt;enumeration value="Gd"/>
 *     &lt;enumeration value="Tb"/>
 *     &lt;enumeration value="Dy"/>
 *     &lt;enumeration value="Ho"/>
 *     &lt;enumeration value="Er"/>
 *     &lt;enumeration value="Tm"/>
 *     &lt;enumeration value="Yb"/>
 *     &lt;enumeration value="Lu"/>
 *     &lt;enumeration value="Hf"/>
 *     &lt;enumeration value="Ta"/>
 *     &lt;enumeration value="W"/>
 *     &lt;enumeration value="Re"/>
 *     &lt;enumeration value="Os"/>
 *     &lt;enumeration value="Ir"/>
 *     &lt;enumeration value="Pt"/>
 *     &lt;enumeration value="Au"/>
 *     &lt;enumeration value="Hg"/>
 *     &lt;enumeration value="Tl"/>
 *     &lt;enumeration value="Pb"/>
 *     &lt;enumeration value="Bi"/>
 *     &lt;enumeration value="Po"/>
 *     &lt;enumeration value="At"/>
 *     &lt;enumeration value="Rn"/>
 *     &lt;enumeration value="Fr"/>
 *     &lt;enumeration value="Ra"/>
 *     &lt;enumeration value="Ac"/>
 *     &lt;enumeration value="Th"/>
 *     &lt;enumeration value="Pa"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="Np"/>
 *     &lt;enumeration value="Pu"/>
 *     &lt;enumeration value="Am"/>
 *     &lt;enumeration value="Cm"/>
 *     &lt;enumeration value="Bk"/>
 *     &lt;enumeration value="Cf"/>
 *     &lt;enumeration value="Es"/>
 *     &lt;enumeration value="Fm"/>
 *     &lt;enumeration value="Md"/>
 *     &lt;enumeration value="No"/>
 *     &lt;enumeration value="Lr"/>
 *     &lt;enumeration value="Rf"/>
 *     &lt;enumeration value="Db"/>
 *     &lt;enumeration value="Sg"/>
 *     &lt;enumeration value="Bh"/>
 *     &lt;enumeration value="Hs"/>
 *     &lt;enumeration value="Mt"/>
 *     &lt;enumeration value="Uun"/>
 *     &lt;enumeration value="Uuu"/>
 *     &lt;enumeration value="Uub"/>
 *     &lt;enumeration value="Uuq"/>
 *     &lt;enumeration value="Uuh"/>
 *     &lt;enumeration value="Uuo"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChemicalElementSymbolType")
@XmlEnum
public enum ChemicalElementSymbolType {


    /**
     * 
     * 	    Hydrogen
     * 	  
     * 
     */
    H("H"),

    /**
     * 
     * 	    Helium
     * 	  
     * 
     */
    @XmlEnumValue("He")
    HE("He"),

    /**
     * 
     * 	    Lithium
     * 	  
     * 
     */
    @XmlEnumValue("Li")
    LI("Li"),

    /**
     * 
     * 	    Beryllium
     * 	  
     * 
     */
    @XmlEnumValue("Be")
    BE("Be"),

    /**
     * 
     * 	    Boron
     * 	  
     * 
     */
    B("B"),

    /**
     * 
     * 	    Carbon
     * 	  
     * 
     */
    C("C"),

    /**
     * 
     * 	    Nitrogen
     * 	  
     * 
     */
    N("N"),

    /**
     * 
     * 	    Oxygen
     * 	  
     * 
     */
    O("O"),

    /**
     * 
     * 	    Fluorine
     * 	  
     * 
     */
    F("F"),

    /**
     * 
     * 	    Neon
     * 	  
     * 
     */
    @XmlEnumValue("Ne")
    NE("Ne"),

    /**
     * 
     * 	    Sodium
     * 	  
     * 
     */
    @XmlEnumValue("Na")
    NA("Na"),

    /**
     * 
     * 	    Magnesium
     * 	  
     * 
     */
    @XmlEnumValue("Mg")
    MG("Mg"),

    /**
     * 
     * 	    Aluminium
     * 	  
     * 
     */
    @XmlEnumValue("Al")
    AL("Al"),

    /**
     * 
     * 	    Silicon
     * 	  
     * 
     */
    @XmlEnumValue("Si")
    SI("Si"),

    /**
     * 
     * 	    Phosphorus
     * 	  
     * 
     */
    P("P"),

    /**
     * 
     * 	    Sulfur
     * 	  
     * 
     */
    S("S"),

    /**
     * 
     * 	    Chlorine
     * 	  
     * 
     */
    @XmlEnumValue("Cl")
    CL("Cl"),

    /**
     * 
     * 	    Argon
     * 	  
     * 
     */
    @XmlEnumValue("Ar")
    AR("Ar"),

    /**
     * 
     * 	    Potassium
     * 	  
     * 
     */
    K("K"),

    /**
     * 
     * 	    Calcium
     * 	  
     * 
     */
    @XmlEnumValue("Ca")
    CA("Ca"),

    /**
     * 
     * 	    Scandium
     * 	  
     * 
     */
    @XmlEnumValue("Sc")
    SC("Sc"),

    /**
     * 
     * 	    Titanium
     * 	  
     * 
     */
    @XmlEnumValue("Ti")
    TI("Ti"),

    /**
     * 
     * 	    Vanadium
     * 	  
     * 
     */
    V("V"),

    /**
     * 
     * 	    Chromium
     * 	  
     * 
     */
    @XmlEnumValue("Cr")
    CR("Cr"),

    /**
     * 
     * 	    Manganese
     * 	  
     * 
     */
    @XmlEnumValue("Mn")
    MN("Mn"),

    /**
     * 
     * 	    Iron
     * 	  
     * 
     */
    @XmlEnumValue("Fe")
    FE("Fe"),

    /**
     * 
     * 	    Cobalt
     * 	  
     * 
     */
    @XmlEnumValue("Co")
    CO("Co"),

    /**
     * 
     * 	    Nickel
     * 	  
     * 
     */
    @XmlEnumValue("Ni")
    NI("Ni"),

    /**
     * 
     * 	    Copper
     * 	  
     * 
     */
    @XmlEnumValue("Cu")
    CU("Cu"),

    /**
     * 
     * 	    Zinc
     * 	  
     * 
     */
    @XmlEnumValue("Zn")
    ZN("Zn"),

    /**
     * 
     * 	    Gallium
     * 	  
     * 
     */
    @XmlEnumValue("Ga")
    GA("Ga"),

    /**
     * 
     * 	    Germanium
     * 	  
     * 
     */
    @XmlEnumValue("Ge")
    GE("Ge"),

    /**
     * 
     * 	    Arsenic
     * 	  
     * 
     */
    @XmlEnumValue("As")
    AS("As"),

    /**
     * 
     * 	    Selenium
     * 	  
     * 
     */
    @XmlEnumValue("Se")
    SE("Se"),

    /**
     * 
     * 	    Bromine
     * 	  
     * 
     */
    @XmlEnumValue("Br")
    BR("Br"),

    /**
     * 
     * 	    Krypton
     * 	  
     * 
     */
    @XmlEnumValue("Kr")
    KR("Kr"),

    /**
     * 
     * 	    Rubidium
     * 	  
     * 
     */
    @XmlEnumValue("Rb")
    RB("Rb"),

    /**
     * 
     * 	    Strontium
     * 	  
     * 
     */
    @XmlEnumValue("Sr")
    SR("Sr"),

    /**
     * 
     * 	    Yttrium
     * 	  
     * 
     */
    Y("Y"),

    /**
     * 
     * 	    Zirconium
     * 	  
     * 
     */
    @XmlEnumValue("Zr")
    ZR("Zr"),

    /**
     * 
     * 	    Niobium
     * 	  
     * 
     */
    @XmlEnumValue("Nb")
    NB("Nb"),

    /**
     * 
     * 	    Molybdenum
     * 	  
     * 
     */
    @XmlEnumValue("Mo")
    MO("Mo"),

    /**
     * 
     * 	    Technetium
     * 	  
     * 
     */
    @XmlEnumValue("Tc")
    TC("Tc"),

    /**
     * 
     * 	    Ruthenium
     * 	  
     * 
     */
    @XmlEnumValue("Ru")
    RU("Ru"),

    /**
     * 
     * 	    Rhodium
     * 	  
     * 
     */
    @XmlEnumValue("Rh")
    RH("Rh"),

    /**
     * 
     * 	    Palladium
     * 	  
     * 
     */
    @XmlEnumValue("Pd")
    PD("Pd"),

    /**
     * 
     * 	    Silver
     * 	  
     * 
     */
    @XmlEnumValue("Ag")
    AG("Ag"),

    /**
     * 
     * 	    Cadmium
     * 	  
     * 
     */
    @XmlEnumValue("Cd")
    CD("Cd"),

    /**
     * 
     * 	    Indium
     * 	  
     * 
     */
    @XmlEnumValue("In")
    IN("In"),

    /**
     * 
     * 	    Tin
     * 	  
     * 
     */
    @XmlEnumValue("Sn")
    SN("Sn"),

    /**
     * 
     * 	    Antimony
     * 	  
     * 
     */
    @XmlEnumValue("Sb")
    SB("Sb"),

    /**
     * 
     * 	    Tellurium
     * 	  
     * 
     */
    @XmlEnumValue("Te")
    TE("Te"),

    /**
     * 
     * 	    Iodine
     * 	  
     * 
     */
    I("I"),

    /**
     * 
     * 	    Xenon
     * 	  
     * 
     */
    @XmlEnumValue("Xe")
    XE("Xe"),

    /**
     * 
     * 	    Caesium
     * 	  
     * 
     */
    @XmlEnumValue("Cs")
    CS("Cs"),

    /**
     * 
     * 	    Barium
     * 	  
     * 
     */
    @XmlEnumValue("Ba")
    BA("Ba"),

    /**
     * 
     * 	    Lanthanum
     * 	  
     * 
     */
    @XmlEnumValue("La")
    LA("La"),

    /**
     * 
     * 	    Cerium
     * 	  
     * 
     */
    @XmlEnumValue("Ce")
    CE("Ce"),

    /**
     * 
     * 	    Praseodymium
     * 	  
     * 
     */
    @XmlEnumValue("Pr")
    PR("Pr"),

    /**
     * 
     * 	    Neodymium
     * 	  
     * 
     */
    @XmlEnumValue("Nd")
    ND("Nd"),

    /**
     * 
     * 	    Promethium
     * 	  
     * 
     */
    @XmlEnumValue("Pm")
    PM("Pm"),

    /**
     * 
     * 	    Samarium
     * 	  
     * 
     */
    @XmlEnumValue("Sm")
    SM("Sm"),

    /**
     * 
     * 	    Europium
     * 	  
     * 
     */
    @XmlEnumValue("Eu")
    EU("Eu"),

    /**
     * 
     * 	    Gadolinium
     * 	  
     * 
     */
    @XmlEnumValue("Gd")
    GD("Gd"),

    /**
     * 
     * 	    Terbium
     * 	  
     * 
     */
    @XmlEnumValue("Tb")
    TB("Tb"),

    /**
     * 
     * 	    Dysprosium
     * 	  
     * 
     */
    @XmlEnumValue("Dy")
    DY("Dy"),

    /**
     * 
     * 	    Holmium
     * 	  
     * 
     */
    @XmlEnumValue("Ho")
    HO("Ho"),

    /**
     * 
     * 	    Erbium
     * 	  
     * 
     */
    @XmlEnumValue("Er")
    ER("Er"),

    /**
     * 
     * 	    Thulium
     * 	  
     * 
     */
    @XmlEnumValue("Tm")
    TM("Tm"),

    /**
     * 
     * 	    Ytterbium
     * 	  
     * 
     */
    @XmlEnumValue("Yb")
    YB("Yb"),

    /**
     * 
     * 	    Lutetium
     * 	  
     * 
     */
    @XmlEnumValue("Lu")
    LU("Lu"),

    /**
     * 
     * 	    Hafnium
     * 	  
     * 
     */
    @XmlEnumValue("Hf")
    HF("Hf"),

    /**
     * 
     * 	    Tantalum
     * 	  
     * 
     */
    @XmlEnumValue("Ta")
    TA("Ta"),

    /**
     * 
     * 	    Tungsten
     * 	  
     * 
     */
    W("W"),

    /**
     * 
     * 	    Rhenium
     * 	  
     * 
     */
    @XmlEnumValue("Re")
    RE("Re"),

    /**
     * 
     * 	    Osmium
     * 	  
     * 
     */
    @XmlEnumValue("Os")
    OS("Os"),

    /**
     * 
     * 	    Iridium
     * 	  
     * 
     */
    @XmlEnumValue("Ir")
    IR("Ir"),

    /**
     * 
     * 	    Platinum
     * 	  
     * 
     */
    @XmlEnumValue("Pt")
    PT("Pt"),

    /**
     * 
     * 	    Gold
     * 	  
     * 
     */
    @XmlEnumValue("Au")
    AU("Au"),

    /**
     * 
     * 	    Mercury
     * 	  
     * 
     */
    @XmlEnumValue("Hg")
    HG("Hg"),

    /**
     * 
     * 	    Thallium
     * 	  
     * 
     */
    @XmlEnumValue("Tl")
    TL("Tl"),

    /**
     * 
     * 	    Lead
     * 	  
     * 
     */
    @XmlEnumValue("Pb")
    PB("Pb"),

    /**
     * 
     * 	    Bismuth
     * 	  
     * 
     */
    @XmlEnumValue("Bi")
    BI("Bi"),

    /**
     * 
     * 	    Polonium
     * 	  
     * 
     */
    @XmlEnumValue("Po")
    PO("Po"),

    /**
     * 
     * 	    Astatine
     * 	  
     * 
     */
    @XmlEnumValue("At")
    AT("At"),

    /**
     * 
     * 	    Radon
     * 	  
     * 
     */
    @XmlEnumValue("Rn")
    RN("Rn"),

    /**
     * 
     * 	    Francium
     * 	  
     * 
     */
    @XmlEnumValue("Fr")
    FR("Fr"),

    /**
     * 
     * 	    Radium
     * 	  
     * 
     */
    @XmlEnumValue("Ra")
    RA("Ra"),

    /**
     * 
     * 	    Actinium
     * 	  
     * 
     */
    @XmlEnumValue("Ac")
    AC("Ac"),

    /**
     * 
     * 	    Thorium
     * 	  
     * 
     */
    @XmlEnumValue("Th")
    TH("Th"),

    /**
     * 
     * 	    Protactinium
     * 	  
     * 
     */
    @XmlEnumValue("Pa")
    PA("Pa"),

    /**
     * 
     * 	    Uranium
     * 	  
     * 
     */
    U("U"),

    /**
     * 
     * 	    Neptunium
     * 	  
     * 
     */
    @XmlEnumValue("Np")
    NP("Np"),

    /**
     * 
     * 	    Plutonium
     * 	  
     * 
     */
    @XmlEnumValue("Pu")
    PU("Pu"),

    /**
     * 
     * 	    Americium
     * 	  
     * 
     */
    @XmlEnumValue("Am")
    AM("Am"),

    /**
     * 
     * 	    Curium
     * 	  
     * 
     */
    @XmlEnumValue("Cm")
    CM("Cm"),

    /**
     * 
     * 	    Berkelium
     * 	  
     * 
     */
    @XmlEnumValue("Bk")
    BK("Bk"),

    /**
     * 
     * 	    Californium
     * 	  
     * 
     */
    @XmlEnumValue("Cf")
    CF("Cf"),

    /**
     * 
     * 	    Einsteinium
     * 	  
     * 
     */
    @XmlEnumValue("Es")
    ES("Es"),

    /**
     * 
     * 	    Fermium
     * 	  
     * 
     */
    @XmlEnumValue("Fm")
    FM("Fm"),

    /**
     * 
     * 	    Mendelevium
     * 	  
     * 
     */
    @XmlEnumValue("Md")
    MD("Md"),

    /**
     * 
     * 	    Nobelium
     * 	  
     * 
     */
    @XmlEnumValue("No")
    NO("No"),

    /**
     * 
     * 	    Lawrencium
     * 	  
     * 
     */
    @XmlEnumValue("Lr")
    LR("Lr"),

    /**
     * 
     * 	    Rutherfordium
     * 	  
     * 
     */
    @XmlEnumValue("Rf")
    RF("Rf"),

    /**
     * 
     * 	    Dubnium
     * 	  
     * 
     */
    @XmlEnumValue("Db")
    DB("Db"),

    /**
     * 
     * 	    Seaborgium
     * 	  
     * 
     */
    @XmlEnumValue("Sg")
    SG("Sg"),

    /**
     * 
     * 	    Bohrium
     * 	  
     * 
     */
    @XmlEnumValue("Bh")
    BH("Bh"),

    /**
     * 
     * 	    Hassium
     * 	  
     * 
     */
    @XmlEnumValue("Hs")
    HS("Hs"),

    /**
     * 
     * 	    Meitnerium
     * 	  
     * 
     */
    @XmlEnumValue("Mt")
    MT("Mt"),

    /**
     * 
     * 	    Ununnilium
     * 	  
     * 
     */
    @XmlEnumValue("Uun")
    UUN("Uun"),

    /**
     * 
     * 	    Unununium
     * 	  
     * 
     */
    @XmlEnumValue("Uuu")
    UUU("Uuu"),

    /**
     * 
     * 	    Ununbium
     * 	  
     * 
     */
    @XmlEnumValue("Uub")
    UUB("Uub"),

    /**
     * 
     * 	    Ununquadium
     * 	  
     * 
     */
    @XmlEnumValue("Uuq")
    UUQ("Uuq"),

    /**
     * 
     * 	    Ununhexium
     * 	  
     * 
     */
    @XmlEnumValue("Uuh")
    UUH("Uuh"),

    /**
     * 
     * 	    Ununoctium
     * 	  
     * 
     */
    @XmlEnumValue("Uuo")
    UUO("Uuo");
    private final String value;

    ChemicalElementSymbolType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChemicalElementSymbolType fromValue(String v) {
        for (ChemicalElementSymbolType c: ChemicalElementSymbolType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
