//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 11:59:10 AM EDT 
//


package org.eclipse.ice.datastructures.batteryml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CSWTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CSWTypeType">
 *   &lt;restriction base="{BatteryML:2.0}ShortTokenType">
 *     &lt;enumeration value="DualFoil"/>
 *     &lt;enumeration value="RC"/>
 *     &lt;enumeration value="NTG"/>
 *     &lt;enumeration value="CellSandwichOther"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CSWTypeType")
@XmlEnum
public enum CSWTypeType {


    /**
     * Dual foil model.
     * 
     */
    @XmlEnumValue("DualFoil")
    DUAL_FOIL("DualFoil"),

    /**
     * RC.
     * 
     */
    RC("RC"),

    /**
     * NTG.
     * 
     */
    NTG("NTG"),

    /**
     * Other cell sandwich type.
     * 
     */
    @XmlEnumValue("CellSandwichOther")
    CELL_SANDWICH_OTHER("CellSandwichOther");
    private final String value;

    CSWTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CSWTypeType fromValue(String v) {
        for (CSWTypeType c: CSWTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
