//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 11:59:10 AM EDT 
//


package org.eclipse.ice.datastructures.batteryml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 	Main instance of battery simulation type. Contains all the hierarchical
 * 	components of the simulation instance.
 *       
 * 
 * <p>Java class for SimulationAbstractType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimulationAbstractType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Control" type="{BatteryML:2.0}CategoryNoIdType" minOccurs="0"/>
 *         &lt;element name="Mesh" type="{BatteryML:2.0}CategoryNoIdType" minOccurs="0"/>
 *         &lt;element name="Operating_Conditions" type="{BatteryML:2.0}CategoryNoIdType" minOccurs="0"/>
 *         &lt;element name="Initial_Conditions" type="{BatteryML:2.0}CategoryNoIdType" minOccurs="0"/>
 *         &lt;element name="Scenario" type="{BatteryML:2.0}CategoryNoIdType" minOccurs="0"/>
 *         &lt;element name="Solution_Strategy" type="{BatteryML:2.0}CategoryNoIdType" minOccurs="0"/>
 *         &lt;element name="Device" type="{BatteryML:2.0}DeviceRefType" minOccurs="0"/>
 *         &lt;element ref="{BatteryML:2.0}Parameters" minOccurs="0"/>
 *         &lt;group ref="{BatteryML:2.0}ElementInfoGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{BatteryML:2.0}ShortTokenType" />
 *       &lt;attribute name="type" type="{BatteryML:2.0}ShortStringType" />
 *       &lt;attribute name="id" type="{BatteryML:2.0}ShortNameType" />
 *       &lt;attribute name="idref" type="{BatteryML:2.0}ShortNameType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimulationAbstractType", propOrder = {
    "control",
    "mesh",
    "operatingConditions",
    "initialConditions",
    "scenario",
    "solutionStrategy",
    "device",
    "parameters",
    "description",
    "comment",
    "documentation"
})
@XmlSeeAlso({
    SimulationDBType.class,
    SimulationType.class
})
public abstract class SimulationAbstractType {

    @XmlElement(name = "Control")
    protected CategoryNoIdType control;
    @XmlElement(name = "Mesh")
    protected CategoryNoIdType mesh;
    @XmlElement(name = "Operating_Conditions")
    protected CategoryNoIdType operatingConditions;
    @XmlElement(name = "Initial_Conditions")
    protected CategoryNoIdType initialConditions;
    @XmlElement(name = "Scenario")
    protected CategoryNoIdType scenario;
    @XmlElement(name = "Solution_Strategy")
    protected CategoryNoIdType solutionStrategy;
    @XmlElement(name = "Device")
    protected DeviceRefType device;
    @XmlElement(name = "Parameters")
    protected Parameters parameters;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "Documentation")
    protected String documentation;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String idref;

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryNoIdType }
     *     
     */
    public CategoryNoIdType getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryNoIdType }
     *     
     */
    public void setControl(CategoryNoIdType value) {
        this.control = value;
    }

    /**
     * Gets the value of the mesh property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryNoIdType }
     *     
     */
    public CategoryNoIdType getMesh() {
        return mesh;
    }

    /**
     * Sets the value of the mesh property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryNoIdType }
     *     
     */
    public void setMesh(CategoryNoIdType value) {
        this.mesh = value;
    }

    /**
     * Gets the value of the operatingConditions property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryNoIdType }
     *     
     */
    public CategoryNoIdType getOperatingConditions() {
        return operatingConditions;
    }

    /**
     * Sets the value of the operatingConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryNoIdType }
     *     
     */
    public void setOperatingConditions(CategoryNoIdType value) {
        this.operatingConditions = value;
    }

    /**
     * Gets the value of the initialConditions property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryNoIdType }
     *     
     */
    public CategoryNoIdType getInitialConditions() {
        return initialConditions;
    }

    /**
     * Sets the value of the initialConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryNoIdType }
     *     
     */
    public void setInitialConditions(CategoryNoIdType value) {
        this.initialConditions = value;
    }

    /**
     * Gets the value of the scenario property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryNoIdType }
     *     
     */
    public CategoryNoIdType getScenario() {
        return scenario;
    }

    /**
     * Sets the value of the scenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryNoIdType }
     *     
     */
    public void setScenario(CategoryNoIdType value) {
        this.scenario = value;
    }

    /**
     * Gets the value of the solutionStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryNoIdType }
     *     
     */
    public CategoryNoIdType getSolutionStrategy() {
        return solutionStrategy;
    }

    /**
     * Sets the value of the solutionStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryNoIdType }
     *     
     */
    public void setSolutionStrategy(CategoryNoIdType value) {
        this.solutionStrategy = value;
    }

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceRefType }
     *     
     */
    public DeviceRefType getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceRefType }
     *     
     */
    public void setDevice(DeviceRefType value) {
        this.device = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdref() {
        return idref;
    }

    /**
     * Sets the value of the idref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdref(String value) {
        this.idref = value;
    }

}
