<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="apps" nsURI="http://eclipse.org/ice/apps" nsPrefix="developerappstore">
  <eClassifiers xsi:type="ecore:EClass" name="IEnvironment" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The IEnvironment interface provides the data and methods necessary to describe a scientific application environment. It describes the name of the environment, the OS it runs in, and the current running state of the environment, the application being developed in the environment, and the dependencies for that application.  IEnvironments can be created and deleted, stopped and connected or re-connected to."/>
    </eAnnotations>
    <eOperations name="build" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Build this IEnvironment from the given data string. The data string can be formatted using JSon, for example. "/>
      </eAnnotations>
    </eOperations>
    <eOperations name="connect" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Connect to this IEnvironment if it is in a Stopped state. "/>
      </eAnnotations>
    </eOperations>
    <eOperations name="delete" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delete the IEnvironment. "/>
      </eAnnotations>
    </eOperations>
    <eOperations name="stop" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Stop this IEnvironment. This sets the state from Running to Stopped. "/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of this environment"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="fedora">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This environment's operating system. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependentPackages" upperBound="-1"
        eType="#//Package" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of packages that the application in this environment depends on. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryApp" eType="#//Package"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The primary application that this IEnvironment serves for development. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectlauncher" eType="#//ProjectLauncher"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//EnvironmentState"
        defaultValueLiteral="NotCreated">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The state of this IEnvironment. The state can be Running, Stopped, or NotCreated. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentManager">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The EnvironmentManager provides the functionality to create new Environments, list existing available Environments, or load an existing Environment. "/>
    </eAnnotations>
    <eOperations name="create" eType="#//IEnvironment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Create a new Environment from the provided JSON properties string. "/>
      </eAnnotations>
      <eParameters name="dataString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="list" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return a list of String names for each existing Environment. The existing environments are stored internally by Eclipse. "/>
      </eAnnotations>
    </eOperations>
    <eOperations name="get" eType="#//IEnvironment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load the Environment with the provided String name. Existing here means stored and tracked internally by Eclipse Preferences. "/>
      </eAnnotations>
      <eParameters name="environmentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="loadFromFile" eType="#//IEnvironment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load an environment from the provided file. The file type should be the EMF XMI persisted model. This is different from loadExisting as it provides a means to load an environment that Eclipse does not know about. "/>
      </eAnnotations>
      <eParameters name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="persistToString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Persist the given IEnvironment to a String and return it. "/>
      </eAnnotations>
      <eParameters name="environmentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="persistToFile">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Persist the given IEnvironment to an EMF XMI file. "/>
      </eAnnotations>
      <eParameters name="environmentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="listAvailableSpackPackages" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="persistEnvironments">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Persist all IEnvironments to the Eclipse preference store. "/>
      </eAnnotations>
    </eOperations>
    <eOperations name="createEmpty" eType="#//IEnvironment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Create a new IEnvironment of the given type. This is an empty IEnvironment that can then be filled by clients."/>
      </eAnnotations>
      <eParameters name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="loadFromXMI" eType="#//IEnvironment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load an IEnvironment from the existing XMI string. "/>
      </eAnnotations>
      <eParameters name="xmiStr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="loadEnvironments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentCreator" eType="#//EnvironmentCreator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentStorage" lowerBound="1"
        eType="#//EnvironmentStorage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpackPackage" eSuperTypes="#//Package">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The SpackPackage class encapsulates the data required to describe a spack package, and the data need to install the package like the compiler to use, any C++ build flags, and dependencies and dependency providers (for example mpi and mpich, respectively)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compiler" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="gcc@6.3.1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The compiler to use for this package. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cppFlags" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The desired C++ flags. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//SpackDependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectLauncher" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The ProjectLauncher is a high-level interface for creating a new Eclipse Project corresponding to the primary application in the Environment. "/>
    </eAnnotations>
    <eOperations name="launchProject" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Launch the new Eclipse project for the given application. "/>
      </eAnnotations>
      <eParameters name="project" eType="#//SourcePackage"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languageprojectprovider"
        eType="#//LanguageProjectProvider" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Package provides an interface describing a software package for an IEnvironment. It provides name, version, and PackageType data attributes. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="latest"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PackageType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PackageType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="PackageType describes the types of derived Package types an IEnvironment can use. "/>
    </eAnnotations>
    <eLiterals name="OS"/>
    <eLiterals name="Spack" value="1"/>
    <eLiterals name="Source" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourcePackage" eSuperTypes="#//Package">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A SourcePackage is a Package that describes a repository URL, repository branch, and executable command to build the Package from scratch. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="master"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OSPackage" eSuperTypes="#//Package">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The OSPackage represents a package to be installed through the OS provided package manager (like dnf for Fedora, or apt-get for Ubuntu)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpackDependency">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A SpackDependency describes a package's dependency and the dependency provider for that dependency (for example, mpi and mpich)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnvironmentState">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The EnvironmentState enumeration provides a way to describe the current state of an IEnvironment. "/>
    </eAnnotations>
    <eLiterals name="Stopped"/>
    <eLiterals name="Running" value="1"/>
    <eLiterals name="NotCreated" value="2"/>
    <eLiterals name="Created" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentCreator" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The EnvironmentCreator interface provides the functionality to create a new IEnvironment from a string containing the data for the IEnvironment. It is up to realizations to parse the format of the string. "/>
    </eAnnotations>
    <eOperations name="create" eType="#//IEnvironment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Create an IEnvironment from the given data string. "/>
      </eAnnotations>
      <eParameters name="dataString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JsonEnvironmentCreator" eSuperTypes="#//EnvironmentCreator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The JsonEnvironmentCreator is a realization of the EnvironmentCreator that implements the create method to parse the data string as a Json string. "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentStorage" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The EnvironmentStorage interface provides a mechanism for persisting and loading environments. "/>
    </eAnnotations>
    <eOperations name="store">
      <eParameters name="environments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    </eOperations>
    <eOperations name="load" upperBound="-1" eType="#//IEnvironment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageProjectProvider" abstract="true"
      interface="true">
    <eOperations name="createProject">
      <eParameters name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eSubpackages name="docker" nsURI="http://eclipse.org/apps/docker" nsPrefix="dockerenvironment">
    <eClassifiers xsi:type="ecore:EClass" name="DockerEnvironment" eSuperTypes="#//IEnvironment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The DockerEnvironment is a realization of the IEnvironment interface that provides a launch method to create a scientific application environment in a Docker container. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="docker" eType="#//docker/DockerAPI"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Reference to the DockerAPI that enables the building of docker images, creation of docker containers from those images, re-connection to existing 'exited' containers, and the deletion of containers and images. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containerConfiguration"
          eType="#//docker/ContainerConfiguration" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Reference to the container configuration data needed to launch a new docker container. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dockerfile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Reference to the String contents of the Dockerfile created to model this DockerEnvironment."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DockerAPI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The DockerAPI provides a high-level abstraction for performing Docker-specific tasks. "/>
      </eAnnotations>
      <eOperations name="buildImage" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Build the image described by the provided Dockerfile build string. "/>
        </eAnnotations>
        <eParameters name="buildFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="imagename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="createContainer" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Launch a new container from the provided image name and ContainerConfiguration object. "/>
        </eAnnotations>
        <eParameters name="imageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="config" eType="#//docker/ContainerConfiguration"/>
      </eOperations>
      <eOperations name="connectToExistingContainer" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Connect to the container with the given name or id. "/>
        </eAnnotations>
        <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="deleteContainer" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Delete the container with the given name. "/>
        </eAnnotations>
        <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="deleteImage" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Delete the image with the given name. "/>
        </eAnnotations>
        <eParameters name="imageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="stopContainer" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
        <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContainerConfiguration">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The ContainerConfiguration wraps container-specific launch configuration data. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The name of the container. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ephemeral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Indicates whether --rm should be added to the launch. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ports" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A list of ports to open on the container. By default, 22 is already opened. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumesConfig" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The volume mounting string. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="remoteSSHPort" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Reference to the localhost SSH port for the container. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DockerProjectLauncher" eSuperTypes="#//ProjectLauncher">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The DockerPTPProjectLauncher provides a launchProject method that uses the ContainerConfiguration of the current DockerEnvironment to create a new PTP Synchronized Project for the IEnvironment's primary application running in the created docker container. "/>
      </eAnnotations>
      <eOperations name="launchProject" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Launch the new Eclipse project for the given application. "/>
        </eAnnotations>
        <eParameters name="project" eType="#//SourcePackage"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containerconfiguration"
          eType="#//docker/ContainerConfiguration"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="local" nsURI="https://eclipse.org/apps/local" nsPrefix="localenvironment">
    <eClassifiers xsi:type="ecore:EClass" name="LocalEnvironment" eSuperTypes="#//IEnvironment"/>
  </eSubpackages>
</ecore:EPackage>
