<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eclipseapps" nsURI="http://eclipse.org/ice/apps/eclipseimpl"
    nsPrefix="eclipseappsimpl">
  <eClassifiers xsi:type="ecore:EClass" name="EclipseEnvironmentStorage" eSuperTypes="../../org.eclipse.ice.developer.apps/model/apps.ecore#//EnvironmentStorage"/>
  <eClassifiers xsi:type="ecore:EClass" name="DockerPTPSyncProjectLauncher" eSuperTypes="../../org.eclipse.ice.developer.apps/model/apps.ecore#//docker/DockerProjectLauncher">
    <eOperations name="launchProject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Launch the new Eclipse project for the given application. "/>
      </eAnnotations>
      <eParameters name="project" eType="ecore:EClass ../../org.eclipse.ice.developer.apps/model/apps.ecore#//SourcePackage"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EclipseCppProjectProvider" eSuperTypes="../../org.eclipse.ice.developer.apps/model/apps.ecore#//LanguageProjectProvider"/>
</ecore:EPackage>
