//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 11:59:10 AM EDT 
//


package oasis.names.tc.unitsml.schema.xsd.unitsmlschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.unitsml.schema.xsd.unitsmlschema_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Item_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Item");
    private static final QName _PrefixName_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "PrefixName");
    private static final QName _PrefixSet_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "PrefixSet");
    private static final QName _UnitSystem_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitSystem");
    private static final QName _UnitHistory_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitHistory");
    private static final QName _UnitSymbol_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitSymbol");
    private static final QName _ThermodynamicTemperature_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ThermodynamicTemperature");
    private static final QName _Mass_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Mass");
    private static final QName _ItemHistory_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ItemHistory");
    private static final QName _ConversionNote_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ConversionNote");
    private static final QName _EnumeratedRootUnit_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "EnumeratedRootUnit");
    private static final QName _ItemName_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ItemName");
    private static final QName _Time_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Time");
    private static final QName _QuantityName_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "QuantityName");
    private static final QName _UnitsML_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitsML");
    private static final QName _RootUnits_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "RootUnits");
    private static final QName _Unit_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Unit");
    private static final QName _ExternalRootUnit_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ExternalRootUnit");
    private static final QName _Length_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Length");
    private static final QName _UnitVersionHistory_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitVersionHistory");
    private static final QName _QuantityVersionHistory_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "QuantityVersionHistory");
    private static final QName _CountedItem_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "CountedItem");
    private static final QName _CodeListValue_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "CodeListValue");
    private static final QName _ConversionDescription_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ConversionDescription");
    private static final QName _Float64ConversionFrom_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Float64ConversionFrom");
    private static final QName _ItemSymbol_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ItemSymbol");
    private static final QName _ItemVersionHistory_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ItemVersionHistory");
    private static final QName _QuantitySymbol_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "QuantitySymbol");
    private static final QName _LuminousIntensity_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "LuminousIntensity");
    private static final QName _UnitReference_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitReference");
    private static final QName _WSDLConversionFrom_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "WSDLConversionFrom");
    private static final QName _ElectricCurrent_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ElectricCurrent");
    private static final QName _WSDLDescription_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "WSDLDescription");
    private static final QName _Conversions_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Conversions");
    private static final QName _ItemRemark_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ItemRemark");
    private static final QName _UnitDefinition_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitDefinition");
    private static final QName _Prefix_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Prefix");
    private static final QName _UnitRemark_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitRemark");
    private static final QName _AmountOfSubstance_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "AmountOfSubstance");
    private static final QName _UnitName_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitName");
    private static final QName _DimensionSet_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "DimensionSet");
    private static final QName _SpecialConversionFrom_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "SpecialConversionFrom");
    private static final QName _QuantityDefinition_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "QuantityDefinition");
    private static final QName _UnitSet_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "UnitSet");
    private static final QName _PrefixSymbol_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "PrefixSymbol");
    private static final QName _QuantityHistory_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "QuantityHistory");
    private static final QName _QuantitySet_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "QuantitySet");
    private static final QName _CountedItemSet_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "CountedItemSet");
    private static final QName _PlaneAngle_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "PlaneAngle");
    private static final QName _ItemDefinition_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "ItemDefinition");
    private static final QName _Quantity_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Quantity");
    private static final QName _QuantityReference_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "QuantityReference");
    private static final QName _QuantityRemark_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "QuantityRemark");
    private static final QName _Dimension_QNAME = new QName("urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", "Dimension");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.unitsml.schema.xsd.unitsmlschema_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpecialConversionFromType }
     * 
     */
    public SpecialConversionFromType createSpecialConversionFromType() {
        return new SpecialConversionFromType();
    }

    /**
     * Create an instance of {@link CodeListValueType }
     * 
     */
    public CodeListValueType createCodeListValueType() {
        return new CodeListValueType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link WSDLConversionFromType }
     * 
     */
    public WSDLConversionFromType createWSDLConversionFromType() {
        return new WSDLConversionFromType();
    }

    /**
     * Create an instance of {@link LengthType }
     * 
     */
    public LengthType createLengthType() {
        return new LengthType();
    }

    /**
     * Create an instance of {@link UnitsMLType }
     * 
     */
    public UnitsMLType createUnitsMLType() {
        return new UnitsMLType();
    }

    /**
     * Create an instance of {@link RemarkType }
     * 
     */
    public RemarkType createRemarkType() {
        return new RemarkType();
    }

    /**
     * Create an instance of {@link QuantitySetType }
     * 
     */
    public QuantitySetType createQuantitySetType() {
        return new QuantitySetType();
    }

    /**
     * Create an instance of {@link ExternalRootUnitType }
     * 
     */
    public ExternalRootUnitType createExternalRootUnitType() {
        return new ExternalRootUnitType();
    }

    /**
     * Create an instance of {@link CountedItemSetType }
     * 
     */
    public CountedItemSetType createCountedItemSetType() {
        return new CountedItemSetType();
    }

    /**
     * Create an instance of {@link PrefixType }
     * 
     */
    public PrefixType createPrefixType() {
        return new PrefixType();
    }

    /**
     * Create an instance of {@link Float64ConversionFromType }
     * 
     */
    public Float64ConversionFromType createFloat64ConversionFromType() {
        return new Float64ConversionFromType();
    }

    /**
     * Create an instance of {@link RootUnitsType }
     * 
     */
    public RootUnitsType createRootUnitsType() {
        return new RootUnitsType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link PrefixSetType }
     * 
     */
    public PrefixSetType createPrefixSetType() {
        return new PrefixSetType();
    }

    /**
     * Create an instance of {@link PlaneAngleType }
     * 
     */
    public PlaneAngleType createPlaneAngleType() {
        return new PlaneAngleType();
    }

    /**
     * Create an instance of {@link LuminousIntensityType }
     * 
     */
    public LuminousIntensityType createLuminousIntensityType() {
        return new LuminousIntensityType();
    }

    /**
     * Create an instance of {@link AmountOfSubstanceType }
     * 
     */
    public AmountOfSubstanceType createAmountOfSubstanceType() {
        return new AmountOfSubstanceType();
    }

    /**
     * Create an instance of {@link MassType }
     * 
     */
    public MassType createMassType() {
        return new MassType();
    }

    /**
     * Create an instance of {@link DimensionSetType }
     * 
     */
    public DimensionSetType createDimensionSetType() {
        return new DimensionSetType();
    }

    /**
     * Create an instance of {@link ElectricCurrentType }
     * 
     */
    public ElectricCurrentType createElectricCurrentType() {
        return new ElectricCurrentType();
    }

    /**
     * Create an instance of {@link CountedItemType }
     * 
     */
    public CountedItemType createCountedItemType() {
        return new CountedItemType();
    }

    /**
     * Create an instance of {@link HistoryType }
     * 
     */
    public HistoryType createHistoryType() {
        return new HistoryType();
    }

    /**
     * Create an instance of {@link DimensionType }
     * 
     */
    public DimensionType createDimensionType() {
        return new DimensionType();
    }

    /**
     * Create an instance of {@link ThermodynamicTemperatureType }
     * 
     */
    public ThermodynamicTemperatureType createThermodynamicTemperatureType() {
        return new ThermodynamicTemperatureType();
    }

    /**
     * Create an instance of {@link EnumeratedRootUnitType }
     * 
     */
    public EnumeratedRootUnitType createEnumeratedRootUnitType() {
        return new EnumeratedRootUnitType();
    }

    /**
     * Create an instance of {@link SymbolType }
     * 
     */
    public SymbolType createSymbolType() {
        return new SymbolType();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link UnitSetType }
     * 
     */
    public UnitSetType createUnitSetType() {
        return new UnitSetType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link SystemType }
     * 
     */
    public SystemType createSystemType() {
        return new SystemType();
    }

    /**
     * Create an instance of {@link ConversionsType }
     * 
     */
    public ConversionsType createConversionsType() {
        return new ConversionsType();
    }

    /**
     * Create an instance of {@link DefinitionType }
     * 
     */
    public DefinitionType createDefinitionType() {
        return new DefinitionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Item")
    public JAXBElement<ItemType> createItem(ItemType value) {
        return new JAXBElement<ItemType>(_Item_QNAME, ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "PrefixName")
    public JAXBElement<NameType> createPrefixName(NameType value) {
        return new JAXBElement<NameType>(_PrefixName_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrefixSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "PrefixSet")
    public JAXBElement<PrefixSetType> createPrefixSet(PrefixSetType value) {
        return new JAXBElement<PrefixSetType>(_PrefixSet_QNAME, PrefixSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitSystem")
    public JAXBElement<SystemType> createUnitSystem(SystemType value) {
        return new JAXBElement<SystemType>(_UnitSystem_QNAME, SystemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitHistory")
    public JAXBElement<HistoryType> createUnitHistory(HistoryType value) {
        return new JAXBElement<HistoryType>(_UnitHistory_QNAME, HistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SymbolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitSymbol")
    public JAXBElement<SymbolType> createUnitSymbol(SymbolType value) {
        return new JAXBElement<SymbolType>(_UnitSymbol_QNAME, SymbolType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ThermodynamicTemperatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ThermodynamicTemperature")
    public JAXBElement<ThermodynamicTemperatureType> createThermodynamicTemperature(ThermodynamicTemperatureType value) {
        return new JAXBElement<ThermodynamicTemperatureType>(_ThermodynamicTemperature_QNAME, ThermodynamicTemperatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Mass")
    public JAXBElement<MassType> createMass(MassType value) {
        return new JAXBElement<MassType>(_Mass_QNAME, MassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ItemHistory")
    public JAXBElement<HistoryType> createItemHistory(HistoryType value) {
        return new JAXBElement<HistoryType>(_ItemHistory_QNAME, HistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ConversionNote")
    public JAXBElement<NoteType> createConversionNote(NoteType value) {
        return new JAXBElement<NoteType>(_ConversionNote_QNAME, NoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnumeratedRootUnitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "EnumeratedRootUnit")
    public JAXBElement<EnumeratedRootUnitType> createEnumeratedRootUnit(EnumeratedRootUnitType value) {
        return new JAXBElement<EnumeratedRootUnitType>(_EnumeratedRootUnit_QNAME, EnumeratedRootUnitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ItemName")
    public JAXBElement<NameType> createItemName(NameType value) {
        return new JAXBElement<NameType>(_ItemName_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Time")
    public JAXBElement<TimeType> createTime(TimeType value) {
        return new JAXBElement<TimeType>(_Time_QNAME, TimeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "QuantityName")
    public JAXBElement<NameType> createQuantityName(NameType value) {
        return new JAXBElement<NameType>(_QuantityName_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitsMLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitsML")
    public JAXBElement<UnitsMLType> createUnitsML(UnitsMLType value) {
        return new JAXBElement<UnitsMLType>(_UnitsML_QNAME, UnitsMLType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootUnitsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "RootUnits")
    public JAXBElement<RootUnitsType> createRootUnits(RootUnitsType value) {
        return new JAXBElement<RootUnitsType>(_RootUnits_QNAME, RootUnitsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Unit")
    public JAXBElement<UnitType> createUnit(UnitType value) {
        return new JAXBElement<UnitType>(_Unit_QNAME, UnitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalRootUnitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ExternalRootUnit")
    public JAXBElement<ExternalRootUnitType> createExternalRootUnit(ExternalRootUnitType value) {
        return new JAXBElement<ExternalRootUnitType>(_ExternalRootUnit_QNAME, ExternalRootUnitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LengthType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Length")
    public JAXBElement<LengthType> createLength(LengthType value) {
        return new JAXBElement<LengthType>(_Length_QNAME, LengthType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitVersionHistory")
    public JAXBElement<NoteType> createUnitVersionHistory(NoteType value) {
        return new JAXBElement<NoteType>(_UnitVersionHistory_QNAME, NoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "QuantityVersionHistory")
    public JAXBElement<NoteType> createQuantityVersionHistory(NoteType value) {
        return new JAXBElement<NoteType>(_QuantityVersionHistory_QNAME, NoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountedItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "CountedItem")
    public JAXBElement<CountedItemType> createCountedItem(CountedItemType value) {
        return new JAXBElement<CountedItemType>(_CountedItem_QNAME, CountedItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "CodeListValue")
    public JAXBElement<CodeListValueType> createCodeListValue(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_CodeListValue_QNAME, CodeListValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ConversionDescription")
    public JAXBElement<NoteType> createConversionDescription(NoteType value) {
        return new JAXBElement<NoteType>(_ConversionDescription_QNAME, NoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float64ConversionFromType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Float64ConversionFrom")
    public JAXBElement<Float64ConversionFromType> createFloat64ConversionFrom(Float64ConversionFromType value) {
        return new JAXBElement<Float64ConversionFromType>(_Float64ConversionFrom_QNAME, Float64ConversionFromType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SymbolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ItemSymbol")
    public JAXBElement<SymbolType> createItemSymbol(SymbolType value) {
        return new JAXBElement<SymbolType>(_ItemSymbol_QNAME, SymbolType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ItemVersionHistory")
    public JAXBElement<NoteType> createItemVersionHistory(NoteType value) {
        return new JAXBElement<NoteType>(_ItemVersionHistory_QNAME, NoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SymbolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "QuantitySymbol")
    public JAXBElement<SymbolType> createQuantitySymbol(SymbolType value) {
        return new JAXBElement<SymbolType>(_QuantitySymbol_QNAME, SymbolType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LuminousIntensityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "LuminousIntensity")
    public JAXBElement<LuminousIntensityType> createLuminousIntensity(LuminousIntensityType value) {
        return new JAXBElement<LuminousIntensityType>(_LuminousIntensity_QNAME, LuminousIntensityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitReference")
    public JAXBElement<ReferenceType> createUnitReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_UnitReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSDLConversionFromType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "WSDLConversionFrom")
    public JAXBElement<WSDLConversionFromType> createWSDLConversionFrom(WSDLConversionFromType value) {
        return new JAXBElement<WSDLConversionFromType>(_WSDLConversionFrom_QNAME, WSDLConversionFromType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElectricCurrentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ElectricCurrent")
    public JAXBElement<ElectricCurrentType> createElectricCurrent(ElectricCurrentType value) {
        return new JAXBElement<ElectricCurrentType>(_ElectricCurrent_QNAME, ElectricCurrentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "WSDLDescription")
    public JAXBElement<NoteType> createWSDLDescription(NoteType value) {
        return new JAXBElement<NoteType>(_WSDLDescription_QNAME, NoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConversionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Conversions")
    public JAXBElement<ConversionsType> createConversions(ConversionsType value) {
        return new JAXBElement<ConversionsType>(_Conversions_QNAME, ConversionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemarkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ItemRemark")
    public JAXBElement<RemarkType> createItemRemark(RemarkType value) {
        return new JAXBElement<RemarkType>(_ItemRemark_QNAME, RemarkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitDefinition")
    public JAXBElement<DefinitionType> createUnitDefinition(DefinitionType value) {
        return new JAXBElement<DefinitionType>(_UnitDefinition_QNAME, DefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrefixType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Prefix")
    public JAXBElement<PrefixType> createPrefix(PrefixType value) {
        return new JAXBElement<PrefixType>(_Prefix_QNAME, PrefixType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemarkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitRemark")
    public JAXBElement<RemarkType> createUnitRemark(RemarkType value) {
        return new JAXBElement<RemarkType>(_UnitRemark_QNAME, RemarkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountOfSubstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "AmountOfSubstance")
    public JAXBElement<AmountOfSubstanceType> createAmountOfSubstance(AmountOfSubstanceType value) {
        return new JAXBElement<AmountOfSubstanceType>(_AmountOfSubstance_QNAME, AmountOfSubstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitName")
    public JAXBElement<NameType> createUnitName(NameType value) {
        return new JAXBElement<NameType>(_UnitName_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DimensionSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "DimensionSet")
    public JAXBElement<DimensionSetType> createDimensionSet(DimensionSetType value) {
        return new JAXBElement<DimensionSetType>(_DimensionSet_QNAME, DimensionSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecialConversionFromType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "SpecialConversionFrom")
    public JAXBElement<SpecialConversionFromType> createSpecialConversionFrom(SpecialConversionFromType value) {
        return new JAXBElement<SpecialConversionFromType>(_SpecialConversionFrom_QNAME, SpecialConversionFromType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "QuantityDefinition")
    public JAXBElement<DefinitionType> createQuantityDefinition(DefinitionType value) {
        return new JAXBElement<DefinitionType>(_QuantityDefinition_QNAME, DefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "UnitSet")
    public JAXBElement<UnitSetType> createUnitSet(UnitSetType value) {
        return new JAXBElement<UnitSetType>(_UnitSet_QNAME, UnitSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SymbolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "PrefixSymbol")
    public JAXBElement<SymbolType> createPrefixSymbol(SymbolType value) {
        return new JAXBElement<SymbolType>(_PrefixSymbol_QNAME, SymbolType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "QuantityHistory")
    public JAXBElement<HistoryType> createQuantityHistory(HistoryType value) {
        return new JAXBElement<HistoryType>(_QuantityHistory_QNAME, HistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantitySetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "QuantitySet")
    public JAXBElement<QuantitySetType> createQuantitySet(QuantitySetType value) {
        return new JAXBElement<QuantitySetType>(_QuantitySet_QNAME, QuantitySetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountedItemSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "CountedItemSet")
    public JAXBElement<CountedItemSetType> createCountedItemSet(CountedItemSetType value) {
        return new JAXBElement<CountedItemSetType>(_CountedItemSet_QNAME, CountedItemSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaneAngleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "PlaneAngle")
    public JAXBElement<PlaneAngleType> createPlaneAngle(PlaneAngleType value) {
        return new JAXBElement<PlaneAngleType>(_PlaneAngle_QNAME, PlaneAngleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "ItemDefinition")
    public JAXBElement<DefinitionType> createItemDefinition(DefinitionType value) {
        return new JAXBElement<DefinitionType>(_ItemDefinition_QNAME, DefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Quantity")
    public JAXBElement<QuantityType> createQuantity(QuantityType value) {
        return new JAXBElement<QuantityType>(_Quantity_QNAME, QuantityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "QuantityReference")
    public JAXBElement<ReferenceType> createQuantityReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_QuantityReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemarkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "QuantityRemark")
    public JAXBElement<RemarkType> createQuantityRemark(RemarkType value) {
        return new JAXBElement<RemarkType>(_QuantityRemark_QNAME, RemarkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DimensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:unitsml:schema:xsd:UnitsMLSchema-1.0", name = "Dimension")
    public JAXBElement<DimensionType> createDimension(DimensionType value) {
        return new JAXBElement<DimensionType>(_Dimension_QNAME, DimensionType.class, null, value);
    }

}
