package testpackage;

import org.eclipse.ice.dev.annotations.IDataElement;

/**
 * This interface satisfies the dependencies of the @DataElement Annotation and
 * was auto-generated by the ICE Framework.
 */
public interface TestElement extends IDataElement<TestElement> {

	/**
	 * Get test.
	 * @return test
	 */
	public java.lang.String getTest();

	/**
	 * Set test.
	 */
	public void setTest(java.lang.String test);
}